[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[dependencies]
frontend = { path = "../frontend" }
backend = { path = "../backend" }
tempfile = "3.2.0"

[[bin]]
name = "driver"
path = "src/main.rs"
